apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          name: ""
          resources:
            requests:
              cpu: 400m
              memory: 512Mi
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone.yaml@versionStream
          name: ""
          resources: {}
        - image: gcr.io/jenkinsxio-labs-private/jxl:0.0.136
          name: tag-with-new-version
          resources: {}
          script: |
            #!/usr/bin/env bash
            jx step next-version --use-git-tag-only --tag
        - image: gcr.io/jenkinsxio/jx-cli:3.0.684
          name: jx-variables
          resources: {}
          script: |
            #!/usr/bin/env bash
            jx gitops variables
        - image: gcr.io/jenkinsxio/jx:2.1.150
          name: promote-changelog
          resources: {}
          script: |
            #!/bin/bash
            source /workspace/source/.jx/variables.sh
            jx step changelog --version v${VERSION}
        - image: gcr.io/jenkinsxio/jx-cli:3.0.684
          name: promote-helm-release
          resources: {}
          script: |
            #!/usr/bin/env bash
            source /workspace/source/.jx/variables.sh
            cd charts/jenkins-x-crds
            make release
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
